# Generated by Django 4.1.6 on 2023-12-28 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_incomecategory_income_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
