# Generated by Django 4.1.6 on 2024-01-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_accesstoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenses",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100000000, null=True),
        ),
    ]
