# Generated by Django 4.1.6 on 2024-01-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_expenses_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
