# Generated by Django 4.1.6 on 2024-01-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_expenses_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesstoken",
            name="cursor",
            field=models.CharField(blank=True, max_length=200000, null=True),
        ),
    ]
